import type { Cluster, Inquiry } from './types';

export const CLUSTERS: Cluster[] = [
  {
    key: 'intake',
    label: 'Intake',
    stages: [1, 2],
    stageLabel: 'Stages 1-2',
    color: '#334155',
    borderColor: '#334155',
    badgeBg: '#e2e8f0',
  },
  {
    key: 'estimation',
    label: 'Estimation',
    stages: [3, 4, 5, 6, 7],
    stageLabel: 'Stages 3-4-5-6-7',
    color: '#b45309',
    borderColor: '#d97706',
    badgeBg: '#fef3c7',
  },
  {
    key: 'proposal',
    label: 'Proposal',
    stages: [8, 9],
    stageLabel: 'Stages 8-9',
    color: '#1d4ed8',
    borderColor: '#3b82f6',
    badgeBg: '#dbeafe',
  },
  {
    key: 'bid_active',
    label: 'Bid Active',
    stages: [10, 11],
    stageLabel: 'Stages 10-11',
    color: '#15803d',
    borderColor: '#16a34a',
    badgeBg: '#dcfce7',
  },
  {
    key: 'outcome',
    label: 'Outcome',
    stages: [12, 13, 14],
    stageLabel: 'Stages 12-13-14',
    color: '#b91c1c',
    borderColor: '#dc2626',
    badgeBg: '#fee2e2',
  },
];

export const INQUIRIES: Inquiry[] = [
  {
    id: 'OEL/EST/2026/0411',
    client: 'TCE',
    project: 'IOCL Paradip',
    scope: 'Chemical Dosing Skid',
    value: 2.07,
    currency: 'USD',
    valueUnit: 'Mn',
    daysToBid: -68,
    currentStage: 2,
    currentStageName: 'Go / No-Go Review',
    priority: 'P2',
    cluster: 'intake',
  },
  {
    id: 'OEL/EST/2026/0418',
    client: 'EIL',
    project: 'BPCL Bina',
    scope: 'Heat Exchangers — CS/LTCS',
    value: 15.86,
    currency: 'INR',
    valueUnit: 'Cr',
    daysToBid: -72,
    currentStage: 7,
    currentStageName: 'Cost Estimate',
    priority: 'P1',
    cluster: 'estimation',
  },
  {
    id: 'OEL/EST/2026/0404',
    client: 'Wood',
    project: 'QatarEnergy LNG',
    scope: 'Surge Drum + Reflux Drum',
    value: 1.45,
    currency: 'USD',
    valueUnit: 'Mn',
    daysToBid: -58,
    currentStage: 6,
    currentStageName: 'Technical Queries',
    priority: 'P2',
    cluster: 'estimation',
  },
  {
    id: 'OEL/EST/2026/0401',
    client: 'Petrofac',
    project: 'ADNOC Hail',
    scope: 'Filter Coalescer Package',
    value: 3.10,
    currency: 'USD',
    valueUnit: 'Mn',
    daysToBid: -50,
    currentStage: 3,
    currentStageName: 'Document Check & Acknowledgment',
    priority: 'P3',
    cluster: 'estimation',
  },
  {
    id: 'OEL/EST/2026/0398',
    client: 'MECON',
    project: 'NRL Numaligarh',
    scope: 'Air Receiver (5 nos)',
    value: 1.10,
    currency: 'INR',
    valueUnit: 'Cr',
    daysToBid: -44,
    currentStage: 4,
    currentStageName: 'Deviation & Clarification',
    priority: 'P3',
    cluster: 'estimation',
  },
  {
    id: 'OEL/EST/2026/0407',
    client: 'L&T',
    project: 'ONGC HRJ',
    scope: 'Pig Launcher/Receiver (4 nos)',
    value: 4.20,
    currency: 'INR',
    valueUnit: 'Cr',
    daysToBid: -65,
    currentStage: 10,
    currentStageName: 'Bid Submitted',
    priority: 'P2',
    cluster: 'bid_active',
  },
];
